version: '3.1'
services:
  stats-server:
    build: ewm-stat/stat-server
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  stats-db:
    image: postgres:14.6-alpine
    container_name: ewm_stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ewm-main
    image: ewm-main
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-db:
    image: postgres:14.6-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm_main_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres